export const apiUrl = 'http://us-central1-llab-development.cloudfunctions.net/fetch_film_store';

export const filmList = [
          {
            "filmImageUrl": "https://filmstore.vn/wp-content/uploads/2017/12/dscf9333.jpg",
            "filmName": "Kodak Portra 400",
            "filmDate": "2021",
            "filmPrice": "200000",
            "filmStatus": "in",
            "filmCategory": "120",
            "filmType": "Color",
            "filmNewArrival": false,
            "filmShowInList": true,
          },
        {
            "filmImageUrl": "https://filmstore.vn/wp-content/uploads/2017/12/dscf9424-2.jpg",
            "filmName": "Kodak Ektar 100",
            "filmDate": "2021",
            "filmPrice": "170000",
            "filmStatus": "in",
            "filmCategory": "120",
            "filmType": "Color",
            "filmNewArrival": false,
            "filmShowInList": true,
          },
          {
            "filmImageUrl": "https://filmstore.vn/wp-content/uploads/2019/07/images.jpg",
            "filmName": "(SLIDE) FUJI PROVIA 100F",
            "filmDate": "2021",
            "filmPrice": "230000",
            "filmStatus": "in",
            "filmCategory": "120",
            "filmType": "Color",
            "filmNewArrival": false,
            "filmShowInList": true,
          },
          {
            "filmImageUrl": "https://filmstore.vn/wp-content/uploads/2017/12/dscf3481.jpg",
            "filmName": "KODAK TRI-X 400",
            "filmDate": "2021",
            "filmPrice": "170000",
            "filmStatus": "in",
            "filmCategory": "120",
            "filmType": "BW",
            "filmNewArrival": false,
            "filmShowInList": true,
          },
          {
            "filmImageUrl": "https://filmstore.vn/wp-content/uploads/2017/12/dscf9336.jpg",
            "filmName": "ILFORD HP5+ 400",
            "filmDate": "2021",
            "filmPrice": "150000",
            "filmStatus": "in",
            "filmCategory": "120",
            "filmType": "BW",
            "filmNewArrival": false,
            "filmShowInList": true,
          },

          {
            "filmImageUrl": "https://filmstore.vn/wp-content/uploads/2017/11/fcb135por400.jpg",
            "filmName": "Kodak Portra 400",
            "filmDate": "2021",
            "filmPrice": "230000",
            "filmStatus": "in",
            "filmCategory": "135",
            "filmType": "Color",
            "filmNewArrival": false,
            "filmShowInList": true,
          },
          {
            "filmImageUrl": "https://filmstore.vn/wp-content/uploads/2017/12/dscf9357-1.jpg",
            "filmName": "Kodak Ektar 100",
            "filmDate": "2021",
            "filmPrice": "180000",
            "filmStatus": "in",
            "filmCategory": "135",
            "filmType": "Color",
            "filmNewArrival": false,
            "filmShowInList": true,
          },
          {
            "filmImageUrl": "https://filmstore.vn/wp-content/uploads/2017/12/dscf9329-1.jpg",
            "filmName": "Fuji Color C200 (3 PACK)",
            "filmDate": "2021",
            "filmPrice": "105000",
            "filmStatus": "in",
            "filmCategory": "135",
            "filmType": "Color",
            "filmNewArrival": false,
            "filmShowInList": true,
          },
          {
            "filmImageUrl": "https://filmstore.vn/wp-content/uploads/2017/12/dscf9367-1.jpg",
            "filmName": "Kodak Color Plus 200",
            "filmDate": "2021",
            "filmPrice": "80000",
            "filmStatus": "in",
            "filmCategory": "135",
            "filmType": "Color",
            "filmNewArrival": true,
            "filmShowInList": true,
          },
          {
            "filmImageUrl": "https://filmstore.vn/wp-content/uploads/2017/12/dscf9365.jpg",
            "filmName": "Kodak Pro Image 100",
            "filmDate": "2021",
            "filmPrice": "110000",
            "filmStatus": "in",
            "filmCategory": "135",
            "filmType": "Color",
            "filmNewArrival": true,
            "filmShowInList": true,
          },
          {
            "filmImageUrl": "https://filmstore.vn/wp-content/uploads/2018/10/Lomo-100.jpg",
            "filmName": "Lomo Graphy 100",
            "filmDate": "2021",
            "filmPrice": "130000",
            "filmStatus": "in",
            "filmCategory": "135",
            "filmType": "Color",
            "filmNewArrival": true,
            "filmShowInList": true,
          },
         {
            "filmImageUrl": "https://filmstore.vn/wp-content/uploads/2018/10/Lomo-400.jpg",
            "filmName": "Lomo Graphy 400",
            "filmDate": "2021",
            "filmPrice": "170000",
            "filmStatus": "in",
            "filmCategory": "135",
            "filmType": "Color",
            "filmNewArrival": true,
            "filmShowInList": true,
          },
          {
            "filmImageUrl": "https://filmstore.vn/wp-content/uploads/2018/10/KPDAK-GOLD-200.jpg",
            "filmName": "Kodak Gold 200 ",
            "filmDate": "2021",
            "filmPrice": "120000",
            "filmStatus": "in",
            "filmCategory": "135",
            "filmType": "Color",
            "filmNewArrival": true,
            "filmShowInList": true,
          },
          {
            "filmImageUrl": "https://filmstore.vn/wp-content/uploads/2018/10/KODAK-ULTRAMAX-400.jpg",
            "filmName": "Kodak Ultramax",
            "filmDate": "2020",
            "filmPrice": "120000",
            "filmStatus": "in",
            "filmCategory": "135",
            "filmType": "Color",
            "filmNewArrival": true,
            "filmShowInList": true,
          },
          {
            "filmImageUrl": "https://filmstore.vn/wp-content/uploads/2019/07/provia.jpg",
            "filmName": "(SLIDE FILM) PROVIA 100F",
            "filmDate": "2020",
            "filmPrice": "320000",
            "filmStatus": "in",
            "filmCategory": "135",
            "filmType": "Color",
            "filmNewArrival": false,
            "filmShowInList": true,
          },

         {
            "filmImageUrl": "https://filmstore.vn/wp-content/uploads/2017/12/dsc01993.jpg",
            "filmName": "Kodak Vision2  200T",
            "filmDate": "5217",
            "filmPrice": "95000",
            "filmStatus": "in",
            "filmCategory": "135",
            "filmType": "Cine",
            "filmNewArrival": false,
            "filmShowInList": true,
          },
         {
            "filmImageUrl": false,
            "filmName": "FUJI F-250",
            "filmDate": "",
            "filmPrice": "100000",
            "filmStatus": "in",
            "filmCategory": "135",
            "filmType": "Cine",
            "filmNewArrival": false,
            "filmShowInList": true,
          },
         {
            "filmImageUrl": false,
            "filmName": "FUJI F-500",
            "filmDate": "",
            "filmPrice": "95000",
            "filmStatus": "in",
            "filmCategory": "135",
            "filmType": "Cine",
            "filmNewArrival": false,
            "filmShowInList": true,
          },

          {
            "filmImageUrl": "https://filmstore.vn/wp-content/uploads/2017/12/dscf3585-1.jpg",
            "filmName": "FOMAPAN 100",
            "filmDate": "2022",
            "filmPrice": "110000",
            "filmStatus": "in",
            "filmCategory": "135",
            "filmType": "BW",
            "filmNewArrival": false,
            "filmShowInList": true,
          },
          {
            "filmImageUrl": "https://filmstore.vn/wp-content/uploads/2017/12/dscf3580-1.jpg",
            "filmName": "FOMAPAN 400",
            "filmDate": "2022",
            "filmPrice": "130000",
            "filmStatus": "in",
            "filmCategory": "135",
            "filmType": "BW",
            "filmNewArrival": false,
            "filmShowInList": true,
          },
         {
            "filmImageUrl": "https://filmstore.vn/wp-content/uploads/2018/07/fomapan-r-100.jpg",
            "filmName": "FOMAPAN R100 (SLIDE BW)",
            "filmDate": "2020",
            "filmPrice": "180000",
            "filmStatus": "in",
            "filmCategory": "135",
            "filmType": "BW",
            "filmNewArrival": false,
            "filmShowInList": true,
          },
           {
            "filmImageUrl": "https://filmstore.vn/wp-content/uploads/2019/07/kentmere-100-film.jpg",
            "filmName": "KENTERME 100",
            "filmDate": "2020",
            "filmPrice": "120000",
            "filmStatus": "in",
            "filmCategory": "135",
            "filmType": "BW",
            "filmNewArrival": false,
            "filmShowInList": true,
          },
        
          {
            "filmImageUrl": false,
            "filmName": "AGFA APX 100",
            "filmDate": "2022",
            "filmPrice": "125000",
            "filmStatus": "in",
            "filmCategory": "135",
            "filmType": "BW",
            "filmNewArrival": false,
            "filmShowInList": true,
          },

          {
            "filmImageUrl": "https://filmstore.vn/wp-content/uploads/2018/10/Fomapan-100-45.jpg",
            "filmName": "FOMAPAN 100  (25 SHEET)",
            "filmDate": "2020",
            "filmPrice": "550000",
            "filmStatus": "in",
            "filmCategory": "Accessories",
            "filmType": "Sheet Film",
            "filmNewArrival": false,
            "filmShowInList": true,
          },
          {
            "filmImageUrl": "https://filmstore.vn/wp-content/uploads/2018/10/Fomapan-400-45.jpg",
            "filmName": "FOMAPAN 400 (25 SHEET)",
            "filmDate": "202",
            "filmPrice": "630000",
            "filmStatus": "in",
            "filmCategory": "Accessories",
            "filmType": "Sheet Film",
            "filmNewArrival": false,
            "filmShowInList": true,
          },

          {
            "filmImageUrl": false,
            "filmName": "KODAK D76 POWDER (1 GALON)",
            "filmDate": " N/A",
            "filmPrice": "350000",
            "filmStatus": "in",
            "filmCategory": "Chemistry",
            "filmType": "Chemistry",
            "filmNewArrival": false,
            "filmShowInList": true,
          },
          {
            "filmImageUrl": false,
            "filmName": "KODAK HC-110 (100ML )",
            "filmDate": " N/A",
            "filmPrice": "150000",
            "filmStatus": "in",
            "filmCategory": "Chemistry",
            "filmType": "Chemistry",
            "filmNewArrival": false,
            "filmShowInList": true,
          },
          {
            "filmImageUrl": false,
            "filmName": "KODAK FIXER POWDER  1GALON",
            "filmDate": " N/A",
            "filmPrice": "190000",
            "filmStatus": "in",
            "filmCategory": "Chemistry",
            "filmType": "Chemistry",
            "filmNewArrival": false,
            "filmShowInList": true,
          },
          {
            "filmImageUrl": false,
            "filmName": "KODAK FIXER LIQUID (1L)",
            "filmDate": " N/A",
            "filmPrice": "600000",
            "filmStatus": "in",
            "filmCategory": "Chemistry",
            "filmType": "Chemistry",
            "filmNewArrival": false,
            "filmShowInList": true,
          },
          {
            "filmImageUrl": false,
            "filmName": "FOMA FIXER POWDER (TO MAKE 1 L)",
            "filmDate": " N/A",
            "filmPrice": "200000",
            "filmStatus": "in",
            "filmCategory": "Chemistry",
            "filmType": "Chemistry",
            "filmNewArrival": false,
            "filmShowInList": true,
          },
          {
            "filmImageUrl": false,
            "filmName": "FOMADON  LQN DEVELOPER 250 ML",
            "filmDate": " N/A",
            "filmPrice": "230000",
            "filmStatus": "in",
            "filmCategory": "Chemistry",
            "filmType": "Chemistry",
            "filmNewArrival": false,
            "filmShowInList": true,
          },
          {
            "filmImageUrl": false,
            "filmName": "FOMADON  LQR DEVELOPER 250 ML",
            "filmDate": " N/A",
            "filmPrice": "230000",
            "filmStatus": "in",
            "filmCategory": "Chemistry",
            "filmType": "Chemistry",
            "filmNewArrival": false,
            "filmShowInList": true,
          },
          {
            "filmImageUrl": false,
            "filmName": "FOMADON P  DEVELOPER  (POWDER MAKE 1L)",
            "filmDate": " N/A",
            "filmPrice": "205000",
            "filmStatus": "in",
            "filmCategory": "Chemistry",
            "filmType": "Chemistry",
            "filmNewArrival": false,
            "filmShowInList": true,
          },

          {
            "filmImageUrl": "https://filmstore.vn/wp-content/uploads/2017/12/dsc02026.jpg",
            "filmName": "PRINTFILE 135 (10 SHEET)",
            "filmDate": " N/A",
            "filmPrice": "100000",
            "filmStatus": "in",
            "filmCategory": "Accessories",
            "filmType": "Accessories",
            "filmNewArrival": false,
            "filmShowInList": true,
          },
          {
            "filmImageUrl": "https://filmstore.vn/wp-content/uploads/2017/12/dsc02025.jpg",
            "filmName": "PRINTFILE 120 (10 SHEET)",
            "filmDate": " N/A",
            "filmPrice": "100000",
            "filmStatus": "in",
            "filmCategory": "Accessories",
            "filmType": "Accessories",
            "filmNewArrival": false,
            "filmShowInList": true,
          },
          {
            "filmImageUrl": "https://filmstore.vn/wp-content/uploads/2017/12/dscf3479.jpg",
            "filmName": "SLIDE MOUNT 35MM BRAUN",
            "filmDate": " N/A",
            "filmPrice": "10000",
            "filmStatus": "in",
            "filmCategory": "Accessories",
            "filmType": "Accessories",
            "filmNewArrival": false,
            "filmShowInList": true,
          }
        ]
 